export const state = () => ({
  list: [
    {
      id: 1,
      img: '/img/products/1.jpg',
      title: 'Мидии в азиатском стиле',
      description: 'с томатами, сельдереем, красным луком, в соево-лимонном маринаде',
      price: 399,
      categoryId: 1,
      props: ['96 kcal.', '350/10/1 гр.', 'Белки: 11.0 г', 'Жиры: 1.9 г', 'Углеводы: 8.7 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 2,
      img: '/img/products/2.jpg',
      title: 'Бородинские гренки',
      description: 'запеченные со сливочным маслом, сыром пармезан и чесноком. Сервируются с трюфельным соусом',
      price: 250,
      categoryId: 1,
      props: ['529 kcal.', '145/30 гр.', 'Белки: 8.3 г', 'Жиры: 51.1 г', 'Углеводы: 8.9 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 3,
      img: '/img/products/3.jpg',
      title: 'Крылышки цыпленка BBQ',
      description: 'в сингапурском стиле, с листьями каффир-лайма, чесноком и лемонграссом',
      price: 377,
      categoryId: 1,
      props: ['229 kcal.', '203/10 гр.', 'Белки: 14.0 г', 'Жиры: 10.6 г', 'Углеводы: 19.5 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 4,
      img: '/img/products/4.jpg',
      title: 'Креветки на льду',
      description: 'магаданские и тигровые креветки, сваренные в ароматном бульоне',
      price: 1337,
      categoryId: 1,
      props: ['1127 kcal.', '600/10/10/50/50/50/50 гр.', 'Белки: 81.2 г', 'Жиры: 80.6 г', 'Углеводы: 19.3 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 5,
      img: '/img/products/5.jpg',
      title: 'Слабосоленый лосось',
      description: 'со сметанным муссом с красной икрой и хрустящей фокаччей',
      price: 487,
      categoryId: 1,
      props: ['472 kcal.', '75/2/1/2шт/55/10 гр.', 'Белки: 22.0 г', 'Жиры: 26.5 г', 'Углеводы: 36.3 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 6,
      img: '/img/products/6.jpg',
      title: 'Скумбрия-гриль',
      description: 'обжаренная с лимоном, сервируется с молодым картофелем с грибами',
      price: 337,
      categoryId: 1,
      props: ['762 kcal.', '1шт/67 гр.', 'Белки: 46.7 г', 'Жиры: 58.6 г', 'Углеводы: 12.0 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 7,
      img: '/img/products/7.jpg',
      title: 'Запеченный Тай',
      description: 'морской окунь с сезонными овощами в соево-лимонном соусе',
      price: 417,
      categoryId: 1,
      props: ['300 kcal.', '260/10/2/20 гр.', 'Белки: 20.9 г', 'Жиры: 20.0 г', 'Углеводы: 9.1 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 8,
      img: '/img/products/8.jpg',
      title: 'Холодный удон',
      description: 'широкая пшеничная лапша с мидиями, креветками, кальмаром и овощами в кисло-пряном бульоне',
      price: 397,
      categoryId: 1,
      props: ['381 kcal.', '380 гр.', 'Белки: 20.5 г', 'Жиры: 13.0 г', 'Углеводы: 40.5 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 9,
      img: '/img/products/9.jpg',
      title: 'Юдзу салат с лососем',
      description: 'слабосоленый лосось с листьями салата и грейпфрутом, в цитрусовом дрессинге "Юдзу"',
      price: 357,
      categoryId: 1,
      props: ['117 kcal.', '150 гр.', 'Белки: 7.4 г', 'Жиры: 6.4 г', 'Углеводы: 8.4 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 10,
      img: '/img/products/10.jpg',
      title: 'Салат "Нью-Йорк"',
      description: 'cлайсы говядины стриплойн, листья салата, огурец, кинза, зеленый лук и томаты черри в тайском соусе',
      price: 397,
      categoryId: 1,
      props: ['191 kcal.', '190 гр.', 'Белки: 9.2 г', 'Жиры: 11.7 г', 'Углеводы: 12.1 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 11,
      img: '/img/products/11.jpg',
      title: 'Салат с креветками',
      description: 'в хрустящей панировке, с листьями сезонного салата и соусом "Том ям"',
      price: 367,
      categoryId: 1,
      props: [' 230 kcal.', '180 гр.', 'Белки: 8.4 г', 'Жиры: 13.6 г', 'Углеводы: 18.6 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 12,
      img: '/img/products/12.jpg',
      title: 'Тартар из тунца',
      description: 'с трюфельным маслом, авокадо и понзу-цитрусовым дрессингом. Сервируется с "Бородинскими" чипсами',
      price: 477,
      categoryId: 1,
      props: ['274 kcal.', '170/10/1/15 гр.', 'Белки: 21.3 г', 'Жиры: 17.1 г', 'Углеводы: 8.8 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 13,
      img: '/img/products/13.jpg',
      title: 'Spring ролл',
      description: 'ролл "Калифорния" в рисовой бумаге, с рукколой, овощами, крабовым мясом и тигровыми креветками. Сервируется с вьетнамским соусом (2 шт.)',
      price: 477,
      categoryId: 1,
      props: ['281 kcal.', '160/10/25 гр.', 'Белки: 7.3 г', 'Жиры: 16.5 г', 'Углеводы: 25.8 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
    {
      id: 14,
      img: '/img/products/14.jpg',
      title: 'Лёгкий ролл с лососем',
      description: 'в огурце, со спайси тунцом и снежным крабом, с васаби. Сервируется с листьями салата, на кунжутно-соевом соусе (5 шт.)',
      price: 377,
      categoryId: 1,
      props: ['156 kcal.', '155/50 гр.', 'Белки: 11.1 г', 'Жиры: 8.2 г', 'Углеводы: 9.4 г'],
      isNew: true,
      isHit: false,
      isSpicy: false,
      relatedProducts: [2, 3, 4, 5, 6, 7, 8, 9],
    },
  ]
});

export const mutations = {

};
